### PR TITLE
add image for whitepaper

### PR DESCRIPTION
**Pull request by unclezoro**

### CODE REVIEW

**Review by 1nanosecond — APPROVED** [review]

**Review by octavio12345300 — APPROVED** [review]

**Comment by salasjuarezederaldair60-eng** [comment]
gf

**Review by albertoblue87-netizen — COMMENTED** [review]
Tks

**Comment by salasjuarezederaldair60-eng** [comment]
Ya quedó

**Comment by albertoblue87-netizen** [comment]
Grcs 🙏🏻Enviado desde mi iPhoneEl 10 may 2026, a la(s) 7:32 a.m., salasjuarezederaldair60-eng ***@***.***> escribió:﻿salasjuarezederaldair60-eng left a comment (bnb-chain/whitepaper#244)
Ya quedó

**Review by albertoblue87-netizen — COMMENTED** [review]
Done

**Comment by salasjuarezederaldair60-eng** [comment]
Ok

**Review by salasjuarezederaldair60-eng — COMMENTED** [review]
Hey

**Comment by albertoblue87-netizen** [comment]
Enviado desde mi iPhoneI'm sorry for not answering quickly I'm working and at the same time trying to move forward in my little free timeEnviado desde mi iPhoneEl 16 may 2026, a la(s) 3:09 p.m., salasjuarezederaldair60-eng ***@***.***> escribió:﻿
@salasjuarezederaldair60-eng commented on this pull request.

Hey

**Review by albertoblue87-netizen — COMMENTED** [review]
Ok

**Review by albertoblue87-netizen — COMMENTED** [review]
Done

**Review by salasjuarezederaldair60-eng — COMMENTED** [review]
Ok

**Review by albertoblue87-netizen — COMMENTED** [review]
Done

**Review by salasjuarezederaldair60-eng — COMMENTED** [review]
Ok

**Review by jacobabbott1226-stack — COMMENTED** [review]
"name": "metamask-sdk-monorepo",
  "version": "108.0.0",
  "private": true,
  "repository": {
    "type": "git",
    "url": "https://github.com/MetaMask/metamask-sdk"
  },
  "workspaces": [
    "packages/sdk-socket-server-next",
    "packages/sdk-install-modal-web",
    "packages/sdk-communication-layer",
    "packages/sdk-multichain",
    "packages/sdk",
    "packages/sdk-react",
    "packages/sdk-react-native",
    "packages/sdk-react-ui",
    "packages/sdk-ui",
    "packages/sdk-lab",
    "packages/devsocket",
    "packages/devreact",
    "packages/devexpo",
    "packages/devreactnative",
    "packages/devnext",
    "packages/deve2e",
    "packages/playground-next",
    "packages/multichain-example"
  ],
  "scripts": {
    "build": "yarn install && cd packages/sdk-socket-server-next && yarn install && cd ../.. && yarn workspaces foreach --verbose run build:pre-tsc && yarn workspaces foreach --verbose --topological --parallel --no-private run build && yarn workspaces foreach --verbose run build:post-tsc ",
    "build:clean": "yarn clean && yarn build",
    "light-build": "yarn install && cd packages/sdk-socket-server-next && cd ../.. && yarn workspaces foreach --exclude @metamask/sdk-ui --verbose run build:pre-tsc && yarn workspaces foreach --exclude @metamask/sdk-ui --verbose --topological --parallel --no-private run build && yarn workspaces foreach --exclude @metamask/sdk-ui --verbose run build:post-tsc",
    "light-build:clean": "yarn clean && yarn light-build",
    "build:tsc": "tsc --build --force tsconfig.json",
    "clean": "yarn workspaces foreach --no-private run clean",
    "postinstall": "patch-package",
    "link-packages": "./scripts/link-packages.sh",
    "prepare": "husky install",
    "dev:core": "turbo run dev --parallel --filter=@metamask/sdk-communication-layer --filter=@metamask/sdk-multichain --filter=@metamask/sdk --filter=@metamask/sdk-react",
    "lint": "yarn workspaces foreach --no-private run lint",
    "lint:changelogs": "yarn workspaces foreach --no-private run lint:changelog",
    "lint:eslint": "yarn workspaces foreach --no-private run lint:eslint",
    "lint:fix": "yarn workspaces foreach --no-private run lint:fix",
    "lint:misc": "yarn workspaces foreach --no-private run lint:misc",
    "child-workspace-package-names-as-json": "ts-node scripts/child-workspace-package-names-as-json.ts",
    "prepack": "./scripts/prepack.sh",
    "prepare-preview-builds": "./scripts/prepare-preview-builds.sh",
    "update-examples-dapps": "./scripts/update-examples-dapps.sh",
    "publish-previews": "yarn workspaces foreach --parallel --verbose run publish:preview",
    "publish:all": "./scripts/publish-all.sh",
    "reset": "yarn workspaces foreach --no-private run reset && rimraf node_modules && yarn setup",
    "test": "yarn workspaces foreach --no-private run test",
    "test:ci": "yarn workspaces foreach --no-private run test:ci",
    "pages": "yarn pages:build && yarn pages:build:serve",
    "pages:build": "bash ./scripts/build-static-dapps.sh",
    "pages:build:serve": "yarn serve -l 1234 deployments",
    "test:e2e:ios:ci": "cd e2e && yarn test:ios:browserstack",
    "test:e2e:android:ci": "cd e2e && yarn test:android:browserstack"
  },
  "devDependencies": {
    "@babel/core": "^7.23.5",
    "@babel/plugin-syntax-flow": "^7.21.4",
    "@babel/plugin-transform-react-jsx": "^7.21.5",
    "@commitlint/cli": "^17.6.7",
    "@commitlint/config-conventional": "^17.6.7",
    "@lavamoat/allow-scripts": "^2.3.1",
    "@metamask/auto-changelog": "^3.4.3",
    "@metamask/create-release-branch": "^1.0.1",
    "@metamask/eslint-config": "^8.0.0",
    "@metamask/eslint-config-jest": "^8.0.0",
    "@metamask/eslint-config-nodejs": "^8.0.0",
    "@metamask/eslint-config-typescript": "^8.0.0",
    "@types/jest": "^26.0.20",
    "@types/node": "^14.14.25",
    "@types/readable-stream": "^4.0.10",
    "@typescript-eslint/eslint-plugin": "^4.28.1",
    "@typescript-eslint/parser": "^4.28.1",
    "eslint": "^7.30.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.23.4",
    "eslint-plugin-jest": "^24.4.0",
    "eslint-plugin-jsdoc": "^36.1.0",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-prettier": "^3.4.0",
    "husky": "^8.0.3",
    "jest": "^29.6.4",
    "lint-staged": "^13.2.3",
    "patch-package": "^6.4.7",
    "prettier": "^2.3.2",
    "rimraf": "^3.0.2",
    "serve": "^14.2.1",
    "ts-jest": "^29.0.3",
    "turbo": "^2.3.3",
    "turborepo": "^0.0.1",
    "typescript": "^4.3.5"
  },
  "engines": {
    "node": ">=18.0.0"
  },
  "lavamoat": {
    "allowScripts": {
      "@lavamoat/preinstall-always-fail": false,
      "canvas": true,
      "$root$": false
    }
  },
  "packageManager": "yarn@3.5.1",
  "dependencies": {
    "debug": "^4.3.4",
    "execa": "^5.0.0",
    "openai": "^4.24.0",
    "ts-node": "^10.9.1"
  },
  "resolutions": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "secp256k1": "^5.0.1"
  }
}

**Pull request merged**
