### PR TITLE
Update WHITEPAPER.md to fix the toc

### PR DESCRIPTION
**Pull request by unclezoro**

### CODE REVIEW

**Review by 1nanosecond — APPROVED** [review]

**Review by albertoblue87-netizen — COMMENTED** [review]
.📌code wow

**Review by albertoblue87-netizen — COMMENTED** [review]
Tks

**Review by albertoblue87-netizen — COMMENTED** [review]
Tks

**Review by albertoblue87-netizen — COMMENTED** [review]
Tks

**Review by albertoblue87-netizen — COMMENTED** [review]
Tks

**Review by albertoblue87-netizen — COMMENTED** [review]
Done

**Review by albertoblue87-netizen — COMMENTED** [review]
Done

**Review by albertoblue87-netizen — COMMENTED** [review]
Done

**Review by albertoblue87-netizen — COMMENTED** [review]
Done

**Review by albertoblue87-netizen — COMMENTED** [review]
Done

**Review by albertoblue87-netizen — COMMENTED** [review]
Done

**Review by albertoblue87-netizen — COMMENTED** [review]
Done

**Review by albertoblue87-netizen — COMMENTED** [review]
Done

**Review by albertoblue87-netizen — COMMENTED** [review]
Done

**Comment by Doublea2121** [comment]
Thank you

**Review by albertoblue87-netizen — COMMENTED** [review]
Done

**Review by jacobabbott1226-stack — COMMENTED** [review]
Hey fix my wallet man I'm getting hacked if I can't do it then I'll just plug in the hard drive and rug everything I don't care

**Pull request merged**
