### PR TITLE
Filipino translation

### PR DESCRIPTION
**Pull request by ricoz**
Translation of English white paper to Filipino

### CODE REVIEW

**Review by Mehmetbatmaz — DISMISSED** [review]

**Comment by huangsuyu** [comment]
Hello, @ricoz 

The team put some comment in this doc: https://docs.google.com/document/d/1hAXyk-tdbIYGjJTjJEkbm8tNxW-ErC2oFauXor_y75E/edit?usp=sharing

Please update according to the comment when necessary.

Thanks!

**Comment by ricoz** [comment]
> Hello, @ricoz
> 
> The team put some comment in this doc: https://docs.google.com/document/d/1hAXyk-tdbIYGjJTjJEkbm8tNxW-ErC2oFauXor_y75E/edit?usp=sharing
> 
> Please update according to the comment when necessary.
> 
> Thanks!

Hi @huangsuyu will check it out and update, thank you!

**Comment by ricoz** [comment]
Hi @huangsuyu I've applied the improvements, thank you!

**Review by chainwhisper — APPROVED** [review]

**Review by Mongkol67 — APPROVED** [review]

**Comment by kadymarian-spec** [comment]
> Translation of English white paper to Filipino

**Review by kadymarian-spec — APPROVED** [review]

**Pull request merged**
