### PR TITLE
update to BSC v0.2 after BC fusion

### PR DESCRIPTION
**Pull request by unclezoro**
Goal:
This PR revise the whitepaper of BSC after BC fusion, it contains the English and Chinese version.

TODO:
need update the `PUTINGPAPEL` and `Spanish` version

### CODE REVIEW

**Review by huihzhao — APPROVED** [review]

**Review by 1nanosecond — APPROVED** [review]

**Comment by kadymarian-spec** [comment]
> Goal:
> This PR revise the whitepaper of BSC after BC fusion, it contains the English and Chinese version.
> 
> TODO:
> need update the `PUTINGPAPEL` and `Spanish` version

**Review by albertoblue87-netizen — COMMENTED** [review]
Tks

**Review by albertoblue87-netizen — COMMENTED** [review]
Tks

**Review by albertoblue87-netizen — COMMENTED** [review]
Tks

**Review by albertoblue87-netizen — COMMENTED** [review]
Tks

**Review by albertoblue87-netizen — COMMENTED** [review]
Tks

**Review by albertoblue87-netizen — COMMENTED** [review]
Hecho

**Pull request merged**
